package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloApp.idl
* Tuesday, 21 April, 2015 5:13:47 PM IST
*/

public interface HelloOperations 
{
  String hellomessage ();
  void hellomessage (String newHellomessage);
} // interface HelloOperations
